{
 "title": "Juju: OVN Chassis",
 "description": "Dashboard for data from prometheus-ovs-exporter running on ovs-chassis juju charms",
 "tags": [ "charm: layer-ovn" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "query": "prometheus" },
   {
    "name": "juju_model",
    "query": {
     "query": "label_values(ovs_up,juju_model)"
    }
   },
   {
    "name": "juju_model_uuid",
    "query": {
     "query": "label_values(ovs_up{juju_model=\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_application",
    "query": {
     "query": "label_values(ovs_up{juju_model=\"$juju_model\", juju_model_uuid=\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_unit",
    "query": {
     "query": "label_values(ovs_up{juju_model=\"$juju_model\", juju_model_uuid=\"$juju_model_uuid\", juju_application=\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "datapath",
    "query": {
     "query": "label_values(ovs_dp_br_if_total{juju_model=\"$juju_model\", juju_model_uuid=\"$juju_model_uuid\", juju_application=\"$juju_application\", juju_unit=\"$juju_unit\"},datapath)"
    }
   },
   {
    "name": "ovs_bridge",
    "label": "OVS Bridge",
    "query": {
     "query": "label_values(ovs_dp_br_if_total{juju_model=\"$juju_model\", juju_model_uuid=\"$juju_model_uuid\", juju_application=\"$juju_application\", juju_unit=\"$juju_unit\", datapath=\"$datapath\"},bridge)"
    }
   },
   {
    "name": "ovs_interface",
    "query": {
     "query": "label_values(ovs_interface{juju_model=\"$juju_model\", juju_model_uuid=\"$juju_model_uuid\", juju_application=\"$juju_application\", juju_unit=\"$juju_unit\"},name)"
    }
   },
   {
    "name": "ovs_interface_uuid",
    "query": {
     "query": "label_values(ovs_interface{juju_model=\"$juju_model\", juju_model_uuid=\"$juju_model_uuid\", juju_application=\"$juju_application\", juju_unit=\"$juju_unit\", name=\"$ovs_interface\"},uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OVS status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_up{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Datapath: $datapath", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Interface count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "repeat": "ovs_bridge",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_dp_br_if_total{datapath=\"$datapath\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{bridge}}"
    }
   ]
  },
  {
   "title": "Datapath Flow Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ovs_dp_flows{datapath=\"$datapath\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{datapath}}"
    }
   ]
  },
  {
   "title": "Datapath Flow Lookups (per second)",
   "type": "timeseries",
   "description": "A rate of packets incoming to the datapath that either:\n* Hit (match existing flow)\n* Miss (not matching existing flow)\n* Were lost (dropped before reaching userspace)[0]\n\n[0] https://mail.openvswitch.org/pipermail/ovs-discuss/2023-August/052596.html",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(ovs_dp_lookups_hit{datapath=\"$datapath\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "Hit"
    },
    {
     "expr": "rate(ovs_dp_lookups_missed{datapath=\"$datapath\",instance=\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "Missed"
    },
    {
     "expr": "rate(ovs_dp_lookups_lost{datapath=\"$datapath\",instance=\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "Lost"
    }
   ]
  },
  {
   "title": "Megaflow masks",
   "type": "stat",
   "description": "Total number of megaflow masks in the datapath",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_dp_masks_total{datapath=\"$datapath\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Megaflow hit ratio",
   "type": "gauge",
   "description": "The ratio between packets that hit any megaflow mask and total number of packets processed by the datapath (hit/total packets)",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_dp_masks_hit_ratio{datapath=\"$datapath\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Megaflow hits (per second)",
   "type": "timeseries",
   "description": "Number of packets (per second) that are matched by OVS megaflow masks",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 29 },
   "targets": [
    {
     "expr": "rate(ovs_dp_masks_hit{datapath=\"$datapath\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "packets/second"
    }
   ]
  },
  {
   "title": "OVS Interface: $ovs_interface on chassis $juju_unit in model $juju_model ($juju_model_uuid)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Administrative State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_interface_admin_state{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Link State",
   "type": "stat",
   "description": "The observed state of the physical network link of OVS interface",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_interface_link_state{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplex Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_interface_duplex{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Index",
   "type": "stat",
   "description": "Represents the interface index associated with OVS interface",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_interface_if_index{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policing Burst",
   "type": "stat",
   "description": "Maximum burst size for data received on OVS interface, in kb (The default burst size, if set to 0, is 8000 kb)",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_interface_ingress_policing_burst{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policing Rate",
   "type": "stat",
   "description": "Maximum rate for data received on OVS interface, in kbps (If set to 0, then policing is disabled)",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_interface_ingress_policing_burst{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Link speed",
   "type": "stat",
   "description": "The negotiated speed of the physical network link of OVS interface",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_interface_link_speed{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "description": "The currently configured MTU for OVS interface",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovs_interface_mtu{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rx/Tx Bytes",
   "type": "timeseries",
   "description": "Represents the number of received and transmitted bytes by OVS interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ovs_interface_rx_bytes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "Rx"
    },
    {
     "expr": "rate(ovs_interface_tx_bytes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Tx/Rx Packets",
   "type": "timeseries",
   "description": "Represents the number of received and transmitted packets by OVS interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ovs_interface_rx_packets{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "Rx"
    },
    {
     "expr": "rate(ovs_interface_tx_packets{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Rx/Tx Drops",
   "type": "timeseries",
   "description": "Represents the number of output/input packets dropped by OVS interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ovs_interface_rx_dropped{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "Rx"
    },
    {
     "expr": "rate(ovs_interface_tx_dropped{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Link reset",
   "type": "timeseries",
   "description": "The number of times Open vSwitch has observed the link_state of OVS interface change",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "ovs_interface_link_resets{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Rx Errors",
   "type": "timeseries",
   "description": "Various error rates for the received packets on the OVS interface (in packets/s)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ovs_interface_rx_errors{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(ovs_interface_rx_crc_err{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "rx_crc_err"
    },
    {
     "expr": "rate(ovs_interface_rx_frame_err{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "rx_frame_err"
    },
    {
     "expr": "rate(ovs_interface_rx_frame_err{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "rx_over_err"
    },
    {
     "expr": "rate(ovs_interface_rx_missed_errors{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "rx_missed_err"
    }
   ]
  },
  {
   "title": "Tx Errors",
   "type": "timeseries",
   "description": "Error rates for the transmitted packets on the OVS interface (in packets/s)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ovs_interface_tx_errors{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",uuid=\"$ovs_interface_uuid\"}[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}