name: Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm: [central, chassis, dedicated-chassis]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install -y tox

      - name: Run linter
        run: |
          tox -e pep8-$(echo "${{ matrix.charm }}" | tr '-' '_')

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm: [central, chassis, dedicated-chassis]
        python-version: ["3.10", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt install -y tox

      - name: Run Unit tests
        run: |
          tox -e py3-$(echo "${{ matrix.charm }}" | tr '-' '_')

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm: [central, chassis, dedicated-chassis]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install -y tox

      - name: Run coverage
        run: |
          tox -e cover-$(echo "${{ matrix.charm }}" | tr '-' '_')

  build:
    name: Build charm
    needs:
      - lint
      - unit
      - coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        charm: [central, chassis, dedicated-chassis]
        platform: ["ubuntu@24.04", "ubuntu@22.04"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install -y tox
          sudo snap install charmcraft --channel 3.x/stable --classic
          sudo snap install lxd --channel 5.21/stable
          sudo snap set lxd daemon.group=adm
          sudo lxd init --auto

      - name: Clear FORWARD firewall rules
        run: |
          # Docker can inject rules causing firewall conflicts
          sudo iptables -P FORWARD ACCEPT  || true
          sudo ip6tables -P FORWARD ACCEPT || true
          sudo iptables -F FORWARD  || true
          sudo ip6tables -F FORWARD || true

      - name: Build charm
        working-directory: ./ovn-${{ matrix.charm }}
        run: |
          ARCH=$(dpkg-architecture -q DEB_HOST_ARCH)
          charmcraft clean
          charmcraft -v pack --platform ${{ matrix.platform }}:$ARCH

      - name: Store charm as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ovn-${{ matrix.charm }}-${{ matrix.platform }}-charm
          path: ./ovn-${{ matrix.charm }}/*.charm
          retention-days: 7

  parse_tags:
    name: Parse tags in PR commits
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      zaza_pr: ${{ steps.find-zaza-pr.outputs.zaza_pr }}
    steps:
      - name: Get PR commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@198af03565609bb4ed924d1260247b4881f09e7d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Find requested functional test PR
        id: 'find-zaza-pr'
        run: |
          COMMIT_DATA=$(
          cat <<'EOF'
          ${{ steps.get-pr-commits.outputs.commits }}
          EOF
          )

          ZAZA_TAG="Func-test-pr: "
          FUNC_PR=$(jq -r '.[].commit.message' <<< "$COMMIT_DATA" | grep -i "^${ZAZA_TAG}" | tail -1)
          PR_URL=$(echo $FUNC_PR | sed -e "s/^$ZAZA_TAG//I")

          echo "zaza_pr=$PR_URL" >> "$GITHUB_OUTPUT"

  functest:
    name: Functional Tests
    needs:
      - build
      - parse_tags
    strategy:
      fail-fast: false
      matrix:
        charm: [central, chassis, dedicated-chassis]
        bundle: ["noble-caracal", "jammy-caracal"]
        include:
          - bundle: "noble-caracal"
            platform: "ubuntu@24.04"
          - bundle: "jammy-caracal"
            platform: "ubuntu@22.04"
    uses: ./.github/workflows/reusable-functest.yml
    with:
      charm: ${{ matrix.charm }}
      bundle: ${{ matrix.bundle }}
      platform: ${{ matrix.platform }}
      zaza_pr: ${{ needs.parse_tags.outputs.zaza_pr }}
    secrets: inherit
